# Generated by Django 5.0.2 on 2024-04-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_remove_todo_items_todo_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='order',
            new_name='owner',
        ),
    ]
