# Generated by Django 5.0.2 on 2024-02-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='producer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
